### ISSUE TITLE
Can I build DLL for Windows?

### ISSUE THREAD

**Issue by vasicvuk** [Edgio/waflz#268]
Hi,

I wanted to know if there is the possibility to build DLL of `/usr/lib/libwaflz.so` for Windows. Idea is to call it from .NET Core, calling PInvoke on .so is fine on Linux but can I somehow call it on Windows?

**Comment by tinselcity** [comment]
We don't currently support building in Windows and didn't have plans to yet that I'm aware of.  We're actively developing `nginx` support and the [`is2`](https://github.com/EdgeCast/is2) example is somewhat straightforward:
See:
[is2 process call](https://github.com/EdgeCast/waflz/blob/master/util/waflz_server/sx_profile.cc#L189)
