### ISSUE TITLE
Example of using Waflz from C++

### ISSUE THREAD

**Issue by vasicvuk** [Edgio/waflz#269]
It would be great to have an example of how to call Waflz from C++ executing rules on sample request body or response.

**Comment by tinselcity** [comment]
I think the most straight forward example is the internal one using [is2](https://github.com/EdgeCast/is2).

To integrate into a server or even a standalone application:

### Define Callbacks
Define/set callbacks for getting the bits from the http request:
- Define callbacks: see `is2` callbacks: https://github.com/EdgeCast/waflz/blob/master/util/waflz_server/cb.cc 
- Set callbacks: see: https://github.com/EdgeCast/waflz/blob/master/util/waflz_server/waflz_server.cc#L1492 

### Configure with ruleset
This part is somewhat tricky but there's a basic example in the README.md:
- https://github.com/EdgeCast/waflz#usage

`waflz` can consume "modsecurity" rules in a few formats including the native modsecurity rule format:
- https://edgecast.github.io/waflz/waflz_dump.html

### Process
Then call the profile process from the "waf" object:
- example again using `is2`: https://github.com/EdgeCast/waflz/blob/master/util/waflz_server/sx_profile.cc#L189

This might be the best example of how to use:
- https://github.com/EdgeCast/waflz/blob/master/util/waflz_server/sx_profile.cc

Apologies for the complexity.  We probably haven't spent enough time making it easy to use and play with outside of servers, but it was designed with server-less development in mind, especially for mocking in tests:
- https://edgecast.github.io/waflz/overview.html#server-shims
